######################################################################
#
# Copyright (C) Zenoss, Inc. 2013, all rights reserved.
#
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is
# installed.
#
######################################################################

from zope.component import adapts
from zope.interface import implements

from Products.ZenRelations.RelSchema import ToMany, ToManyCont, ToOne
from Products.Zuul.catalog.paths import DefaultPathReporter, relPath
from Products.Zuul.form import schema
from Products.Zuul.infos import ProxyProperty
from Products.Zuul.utils import ZuulMessageFactory as _t

from ZenPacks.zenoss.XenServer import CLASS_NAME, MODULE_NAME
from ZenPacks.zenoss.XenServer.utils import (
    PooledComponent, IPooledComponentInfo, PooledComponentInfo,
    RelationshipInfoProperty,
    updateToOne,
    )


class VIF(PooledComponent):
    '''
    Model class for VIF (virtual interface.)
    '''

    meta_type = portal_type = 'XenServerVIF'

    macaddress = None
    mac_autogenerated = None
    mtu = None
    allowed_operations = None
    currently_attached = None
    vif_device = None
    ipv4_allowed = None
    ipv6_allowed = None
    locking_mode = None
    metrics_ref = None

    _properties = PooledComponent._properties + (
        {'id': 'macaddress', 'type': 'string', 'mode': 'w'},
        {'id': 'mac_autogenerated', 'type': 'bool', 'mode': 'w'},
        {'id': 'mtu', 'type': 'string', 'mode': 'w'},
        {'id': 'allowed_operations', 'type': 'lines', 'mode': 'w'},
        {'id': 'currently_attached', 'type': 'bool', 'mode': 'w'},
        {'id': 'vif_device', 'type': 'string', 'mode': 'w'},
        {'id': 'ipv4_allowed', 'type': 'lines', 'mode': 'w'},
        {'id': 'ipv6_allowed', 'type': 'lines', 'mode': 'w'},
        {'id': 'locking_mode', 'type': 'string', 'mode': 'w'},
        {'id': 'metrics_ref', 'type': 'string', 'mode': 'w'},
        )

    _relations = PooledComponent._relations + (
        ('vm', ToOne(ToManyCont, MODULE_NAME['VM'], 'vifs')),
        ('network', ToOne(ToMany, MODULE_NAME['Network'], 'vifs')),
        )

    def getNetwork(self):
        '''
        Return network id or None.

        Used by modeling.
        '''
        obj = self.network()
        if obj:
            return obj.id

    def setNetwork(self, network_id):
        '''
        Set network by id.

        Used by modeling.
        '''
        updateToOne(
            relationship=self.network,
            root=self.device(),
            type_=CLASS_NAME['Network'],
            id_=network_id)


class IVIFInfo(IPooledComponentInfo):
    '''
    API Info interface for VIF.
    '''

    vm = schema.Entity(title=_t(u'VM'))
    network = schema.Entity(title=_t(u'Network'))

    macaddress = schema.TextLine(title=_t(u'MAC Address'))
    mac_autogenerated = schema.TextLine(title=_t(u'Autogenerate MAC Address'))
    mtu = schema.TextLine(title=_t(u'MTU'))
    allowed_operations = schema.TextLine(title=_t(u'Allowed Operations'))
    currently_attached = schema.TextLine(title=_t(u'Currently Attached'))
    vif_device = schema.TextLine(title=_t(u'Device Name'))
    ipv4_allowed = schema.TextLine(title=_t(u'IPv4 Allowed'))
    ipv6_allowed = schema.TextLine(title=_t(u'IPv6 Allowed'))
    locking_mode = schema.TextLine(title=_t(u'Locking Mode'))


class VIFInfo(PooledComponentInfo):
    '''
    API Info adapter factory for VIF.
    '''

    implements(IVIFInfo)
    adapts(VIF)

    vm = RelationshipInfoProperty('vm')
    network = RelationshipInfoProperty('network')

    macaddress = ProxyProperty('macaddress')
    mac_autogenerated = ProxyProperty('mac_autogenerated')
    mtu = ProxyProperty('mtu')
    allowed_operations = ProxyProperty('allowed_operations')
    currently_attached = ProxyProperty('currently_attached')
    vif_device = ProxyProperty('vif_device')
    ipv4_allowed = ProxyProperty('ipv4_allowed')
    ipv6_allowed = ProxyProperty('ipv6_allowed')
    locking_mode = ProxyProperty('locking_mode')
    metrics_ref = ProxyProperty('metrics_ref')


class VIFPathReporter(DefaultPathReporter):
    '''
    Path reporter for VIF.
    '''

    def getPaths(self):
        paths = super(VIFPathReporter, self).getPaths()

        network = self.context.network()
        if network:
            paths.extend(relPath(network, 'endpoint'))

        vapp = self.context.vm().vmappliance()
        if vapp:
            paths.extend(relPath(vapp, 'endpoint'))

        return paths
